#!/usr/bin/env ruby

#! outputs the game overview as soon as the program is run on the user's terminal
def about()
    puts add_space(" ", "left").colorize(:color => :black, :background => :magenta)
    puts add_space("  __ _  ___ _ __   ___  ___(_)___", "left").colorize(:color => :black, :background => :magenta)
    puts add_space(" / _` |/ _ \\ '_ \\ / _ \\/ __| / __|", "left").colorize(:color => :black, :background => :magenta)
    puts add_space("| (_| |  __/ | | |  __/\\__ \\ \\__ \\", "left").colorize(:color => :black, :background => :magenta)
    puts add_space(" \\__, |\\___|_| |_|\\___||___/_|___/", "left").colorize(:color => :black, :background => :magenta)
    puts add_space(" |___/                                            Task 9.3 by Utkarsh", "left").colorize(:color => :black, :background => :magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("Objective:", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("Player has to reach the end of the map without dying and has to kill", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("as many skulls as possible on the way.", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("10 skulls be summoned and only by killing them all the player can", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("win.  *There would only be one skull on the screen at a moment.", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("Time taken for a new skull to spawn after previous dies is random.", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("Successfully shooting a skull will give 1 point (each) and", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("completing the map will give 5 points (total).", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("Avoid walking on thorns", "left").colorize(:color => :red, :background => :light_magenta)
    puts add_space("Once crossed a portal, you cannot return back!", "left").colorize(:color => :light_yellow, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("Controls: Keyboard", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("[W] Switch Gravity upwards              [S] Switch Gravity downwards", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("[A] Player move backwards               [D] Player move forward", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("[SPACE]                                 Enable Scope", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("[ESCAPE]                                Quit Game", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("Controls: Mouse", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("[RIGHT CLICK] Reload                    [LEFT CLICK] Shoot            ", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("Game Details:", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("Resolution                              1000x730", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("Please plugin headphones for audio affects.", "left").colorize(:color => :light_yellow, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("Copyright Information:", "left").colorize(:color => :black, :background => :light_magenta)
    puts add_space("All media used in this game is either self made or is royalty free", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space("by their respective authors.", "left").colorize(:color => :white, :background => :light_magenta)
    puts add_space(" ", "left").colorize(:color => :black, :background => :light_magenta)
end
